const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');
const prettierConfig = require('eslint-config-prettier/flat');

module.exports = defineConfig([
  expoConfig,
  // Must come after expoConfig so formatting rules that would fight Prettier
  // are switched off rather than switched back on.
  prettierConfig,
  {
    ignores: [
      'dist/*',
      '.expo/*',
      'node_modules/*',
      // Regenerated by `npm run types:db`; not ours to lint.
      'src/types/database.ts',
    ],
  },
  {
    // Scoped to TypeScript files so the @typescript-eslint plugin that
    // expoConfig registers for these patterns is actually in scope.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Half-finished refactors should fail CI rather than ship. `_`-prefixed
      // names stay allowed for deliberately-ignored callback arguments.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
]);
